BlogWeb/Models/Domain/BlogPost.cs
namespace BlogWeb.Models.Domain
{
    public class BlogPost
    {
        public int Id { get; set; }
        public string Heading { get; set; }
        public string PageTitle { get; set; }
        public string Content { get; set; }
        public string ShortDescription { get; set; }
        public string FeaturedImageUrl { get; set; }
        public string Author { get; set; }
    }
}

BlogWeb/Models/ErrorViewModel.cs
namespace BlogWeb.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

BlogWeb/Controllers/AdminPostController.cs
using BlogWeb.Data;
using BlogWeb.Data.Repository;
using BlogWeb.Models.Domain;
using Microsoft.AspNetCore.Mvc;

namespace BlogWeb.Controllers
{
    public class AdminPostController : Controller
    {
        private IRepository _repo;
        public AdminPostController(IRepository repo)
        {
            _repo = repo;
        }

      

        [HttpGet]
        public IActionResult AddPost(int? Id)
        {
            if (Id == null)
            {
                return View(new BlogPost());
            }
            else
            {
                var post = _repo.GetPost((int) Id);  
                return View(post);
            }
        }


        [HttpPost]
        [ActionName("AddPost")]
        public async Task<IActionResult> Edit(BlogPost post) 
        {
            if (post.Id > 0)
                _repo.UpdatePost(post);
            else
            _repo.AddPost(post);

            if(await _repo.SaveChangeAsync())

                return RedirectToAction("AddPost");
            else
                return View(post);
        }

        [HttpGet]
        public async Task<IActionResult> Remove(int Id) 
        {
            _repo.RemovePost(Id);
            await _repo.SaveChangeAsync();
            return RedirectToAction("AddPost");
        }
    }
}

BlogWeb/Controllers/AllPostMenuController.cs
using BlogWeb.Data.Repository;
using BlogWeb.Models.Domain;
using Microsoft.AspNetCore.Mvc;

namespace BlogWeb.Controllers
{
    public class AllPostMenuController : Controller
    {
        private IRepository _repo;
        public AllPostMenuController(IRepository repo)
        {
            _repo = repo;
        }
        public IActionResult AllPostMenu()
        {
            var posts = _repo.GetAllPost();
            return View(posts);
        }
        
        public IActionResult BlogPost(int Id) 
        {
            var post = _repo.GetPost(Id);
            return View(post);
        }

        [HttpPost]
        [ActionName("AddPost")]
        public async Task<IActionResult> AddPost(BlogPost post)
        {
            if (post.Id > 0)
                _repo.UpdatePost(post);
            else
                _repo.AddPost(post);

            if (await _repo.SaveChangeAsync())

                return RedirectToAction("AllPostMenu");
            else
                return View(post);
        }

        [HttpGet]
        public async Task<IActionResult> Remove(int Id)
        {
            _repo.RemovePost(Id);
            await _repo.SaveChangeAsync();
            return RedirectToAction("AllPostMenu");
        }

    }
}

BlogWeb/Controllers/HomeController.cs
using BlogWeb.Data.Repository;
using BlogWeb.Models;
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;

namespace BlogWeb.Controllers
{
    public class HomeController : Controller
    {
       
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
        
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }
        public IActionResult Home()
        {
            return RedirectToAction("Index");
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

BlogWeb/Views/AdminPost/AddPost.cshtml
@model BlogWeb.Models.Domain.BlogPost
@{
}
<div class="bg-secondary bg-black bg-opacity-10 py-2">
    <div class="container">
        <h1>Add New Post - Admin Functionality</h1>
    </div>
</div>
<div class="container py-5">
    <form method="post">
        <input asp-for="Id" type ="hidden"/>
        <div class="mb-3">
            <label class="form-label">Name</label>
            <input type="text" class="form-contol" id="Heading" name="Heading" asp-for="Heading" />
        </div>
        <div class="mb-3">
            <label class="form-label">Content</label>
            <input type="text" class="form-contol" id="Content" name="Content" asp-for="Content" />
        </div>
        <div class="mb-3">
            <label class="form-label">ShortDescription</label>
            <input type="text" class="form-contol" id="ShortDescription" name="ShortDescription" asp-for="ShortDescription" />
        </div>
        <div class="mb-3">
            <label class="form-label">PageTitle</label>
            <input type="text" class="form-contol" id="PageTitle" name="PageTitle" asp-for="PageTitle" />
        </div>
        <div class="mb-3">
            <label class="form-label">FeaturedImageUrl</label>
            <input type="text" class="form-contol" id="FeaturedImageUrl" name="FeaturedImageUrl" asp-for="FeaturedImageUrl" />
        </div>
        <div class="mb-3">
            <label class="form-label">Author</label>
            <input type="text" class="form-contol" id="Author" name="Author" asp-for="Author" />
        </div>
        <div class="mb-3">
            <button type="submit" class="btn btn-dark">Submit</button>
        </div>

    </form>

</div>

BlogWeb/Views/AllPostMenu/AllPostMenu.cshtml
@model IEnumerable<BlogWeb.Models.Domain.BlogPost>
@{

}
<h2>All Post Menu</h2>
<div>
    <ul>
        @foreach (var post in Model)
        {
          <li>
              <a asp-controller="AllPostMenu" asp-action="BlogPost" asp-route-id="@post.Id">
                  @post.Heading
              </a>
                <a asp-controller="AdminPost" asp-action="AddPost" asp-route-id="@post.Id">
                    Edit    
                </a>
                <a asp-controller="AllPostMenu" asp-action="Remove" asp-route-id="@post.Id">
                    Remove
                </a>
          </li>   
        }
    </ul>
</div>

BlogWeb/Views/AllPostMenu/BlogPost.cshtml
@model BlogWeb.Models.Domain.BlogPost
@{

}
<h2>@Model.Heading</h2>
<p>@Model.Content</p>

BlogWeb/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
 
</div>

BlogWeb/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - BlogWeb</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/BlogWeb.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-dark bg-dark border-bottom box-shadow">
            
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>


                        <li class = "nav-item dropdown">
                            <a class="nav-link dropdown-toggle" href ="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                                Admin
                            </a>
                            <ul class="dropdown-menu">
                            <li>
                                <a class=" dropdown-item" asp-area=""
                                   asp-controller="AdminPost"
                                   asp-action="AddPost">Add BlogPost</a>
                            </li>
                            <li>
                                <a class= "dropdown-item" asp-area=""
                                   asp-controller="AllPostMenu"
                                   asp-action="AllPostMenu">AllPostMenu</a>
                            </li>
                            <li>
                                <a class="dropdown-item" asp-area=""
                                   asp-controller="Home"
                                   asp-action="Home">Home</a>
                            </li>

                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div>
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>


    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>